---
abstract: 'Reformat HTML fragment to strict criteria'
author:
  - 'Nicholas Bamber <nicholas@periapt.co.uk>'
build_requires:
  Benchmark: 0
  Perl6::Slurp: 0
  Test::Differences: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Acid
provides:
  Data::FormValidator::Filters::HTML::Acid:
    file: lib/Data/FormValidator/Filters/HTML/Acid.pm
    version: v0.0.1
  HTML::Acid:
    file: lib/HTML/Acid.pm
    version: v0.0.1
  HTML::Acid::Buffer:
    file: lib/HTML/Acid/Buffer.pm
    version: v0.0.1
requires:
  HTML::Parser: 3
  Readonly: 0
  String::Dirify: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.1
